# Generated by Django 5.1.4 on 2024-12-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iteration', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('sub_project', models.CharField(max_length=100)),
                ('team_member', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('completed', '完成'), ('in_progress', '进行中'), ('delay', '延迟'), ('plan', '计划')], max_length=20)),
                ('is_reporting_to_me', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
